### PR TITLE
Ada Starter Pack

### PR DESCRIPTION
**Pull request by philxyz**
Cleaned up License text

### CODE REVIEW

**Comment by philxyz** [comment]
Just realised I don't need to re-submit a pull request. Here it is anyway :D

**Comment by Janzert** [comment]
Having a bit of trouble getting this working. On ubuntu natty (the version used in the contest) running make ends up with this error:

gcc -c -g -O2 -I ants.ads -gnatA mybot.adb  
gcc: error trying to exec 'gnat1': execvp: No such file or directory

Which looks to me like gnat isn't installed properly, but I've tried uninstalling and reinstalling the gnat package and it seems to install fine. Running the command gnat at the command line also seems to run fine.

Running under ubuntu maverick (10.10) I get an error about a missing : on line 33 of ants.adb. My guess was that it wanted a ": Bearing " added to specify the type. But I know no Ada and giving that a try just led to another error. This of course might just be caused by an older compiler version. Getting it working on natty is what is really needed for the contest.

I've also made some changes to get compiler.py working although without being able to get the bot to build I can't test if it's actually working yet. I'm going to merge what is done so far though although it's pretty certainly not quite working yet.

**Comment by philxyz** [comment]
Hi Janzert, I am not sure what could be causing the execvp error however the error on maverick is correct. Unfortunately I had started changing the code and must have committed it before I had checked it. I have now fixed and re-committed the ada bot (which now compiles for me) - the compiler.py might have needed a bit of extra help since I don't really know Python well - or how the file should work out. With your changes it should work fine - basically it compiles as per the makefile so I would imagine they compiler.py would need to do whatever that does in order to work.

Thanks!

**Comment by philxyz** [comment]
Also, try installing the gnat-4.4 package on natty narwhal - maybe it needs that specific version. The code is basic Ada 2005 syntax so it should compile fine.

**Comment by Janzert** [comment]
closing as this is now committed and live. further bugs can be in separate issues.

**Pull request closed without merging**
