### PR TITLE
C# Starter Package for Visual Studio

### PR DESCRIPTION
**Pull request by jmcgonegal**
I've created a rudimentary c# starter package for visual studio users.

### CODE REVIEW

**Comment by amstan** [comment]
Does this compile with the current framework? There is no Visual Studio to use on the server, we use mono. See compile_anything.py for more details.

**Comment by jmcgonegal** [comment]
I'll take a look. I wasn't aware there was a guide to what a starter bot should have.

**Comment by Nehle** [comment]
@armstan - In the last AI challenge, the mono version used supported C# 3.5. If that hasn't changed, this should compile

@jcmcgonegal - good start. Could you try to make it more C# and less Java?

**Comment by amstan** [comment]
Please test it on aichallenge.hypertriangle.com.
Reopen with a link of it in action.

**Pull request closed without merging**
