### PR TITLE
Introducing Clojure support using Leiningen.

### PR DESCRIPTION
**Pull request by i0cus**
- compiler.py to expect Leiningen project.clj file and build uberjar
- run options set to java -jar MyBot.jar
- ExternalCompiler bug fixed (s/log/errors/)
- worker_setup.py changed to fetch and run lein 1.5.2
- Clojure starter package introduced in ants/dist/starter_bots/clojure

Notes:
- Leiningen will require network for first run after installation for every user
  because its files are stored in HOME/.lein and HOME/.m2; So unless project
  is compiled by root (is it?) then compiling machine will require network access.
  This could be change if we had modified version of lein script, but that seemed
  to be pushing it.
- Needs to be solidly tested, I can not run amd64 vbox anywhere, so I only tested
  this by manually running modified Python scripts.

### CODE REVIEW

**Comment by Janzert** [comment]
Not sure I'm understanding the note above correctly, but compilation of submissions will not have network access. Any compilation during the language setup (in worker_setup.py) will have network access and is done as root.

**Comment by i0cus** [comment]
Ok, this means that building will not work with that version of `lein` script. I will try and update it today and/or tomorrow, and then create another pull request.

Is it possible to get worker setup instructions, so I can actually try to test it if I find a 64bit machine?

**Comment by Janzert** [comment]
Unfortunately the full worker setup is still in a state of flux and not yet complete. You can use the worker_setup.py script to get everything basically setup on a fresh OS install. But compilation of bots is not yet sandboxed.

**Comment by i0cus** [comment]
I'm still working on it, will open another pull request when I'm done. For now I'm closing this as invalid.

**Pull request closed without merging**
