### PR TITLE
An online version of the map generator. Available at http://antmapgenerat

### PR DESCRIPTION
**Pull request by Lundgren**
An online version of the map generator. Available at http://antmapgenerator.appspot.com/

### CODE REVIEW

**Comment by mleise** [comment]
Nice little gui for setting the various parameters. When I tried it today I forced a fixed map size of 120 squares, but the generator always answers with 'oops, something went wrong'. Also you got the . and % mixed up, but that is quickly resolved I guess.

**Comment by Lundgren** [comment]
Yeah you're totally right. I fixed the errors now and uploaded here and to AppEngine. Thanks for letting me know  and please try again.

**Comment by serialc** [comment]
While the ASCII map and canvas map match for 8 player configurations, they are rotated (not matching) 90 degrees for 4 and 2 player options. It looks wrong at first glance until you figure out the rotation.

&&&&&
X&&&X
XX&XX
X&&&X
&&&&&

to

&XXX&
&&X&&
&&&&&
&&X&&
&XXX&

**Comment by amstan** [comment]
I don't see what purpose it would be to merge an online map generator in the contest codebase.
What i still await is the symmetric map generator that employs rotation and mirroring. As opposed to antimatroid's translation symmetry.

**Pull request closed without merging**
