### PR TITLE
C Hills

### PR DESCRIPTION
**Pull request by mpolitzer**
Added hill in C, with hill and hill + ant detection

### CODE REVIEW

**Comment by amstan** [comment]
Can you find someone to review this for you?

**Comment by mpolitzer** [comment]
I posted a code review request in the forum @ http://aichallenge.org/forums/viewtopic.php?f=25&t=1782, but nothing so far

**Comment by flagcapper** [comment]
Just from looking at the code, it seems you are ignoring the player identity of a dead ant. Admittedly, I don't think many people use this feature, but you may want to add it just in case someone decides to use it and it's not there. 

Other than that, it looks pretty good. I'll try running it tomorrow to make sure everything works well.

**Comment by mpolitzer** [comment]
Yes, I've noticed that but and got a little confused because the map specs from here: http://aichallenge.org/specification.php#Bot-Input don't say how to mark on the map the diferent enemy ants, the previous used symbol was the upper cased characters, but it clashed with the hills+ants notation. I certainly would like to add the dead ant owner, but I can't quite understand which rule to use to mark them on the map.

**Comment by flagcapper** [comment]
Yeah, I saw that part of the spec too, but I was thinking the player id could simply be stored inside the dead_ants structure and the position on the map could simply be left as an '!'. This would probably mean you would have to set those areas on the map to an unused range of 10 values in _init_map(), and then set those squares back to '!' once you have copied the player id into the structure.

**Comment by flagcapper** [comment]
I added dead ant player support to your code and have pushed it to the main repo now, so I'm closing this.

**Comment by mpolitzer** [comment]
Nice! I'll check it out.

**Pull request closed without merging**
