### PR TITLE
Added 'remember me' functionality

### PR DESCRIPTION
**Pull request by bearoff**
http://aichallenge.org/forums/viewtopic.php?f=21&t=1571

No IP check used - I think it's too much, tell me if no.

(I see, my IDE removed trailing spaces somewhere)

### CODE REVIEW

**Comment by McLeopold** [comment]
Nice work.  This is really close.  Using an md5 hash of a database value is not secure.  I'd rather a guid be generated as the cookie value, then stored in the database encrypted.  This effectively gives the user 2 valid passwords, 1 to use on the login form only and 1 to use from the cookie only.  The guid could be [user name/id]:[salt] so that you only need to store 1 cookie, rather than 2 and we can do the user lookup in the database quickly.  Assume a database field in the user table called login_cookie.  I can update the database and make the changes.

**Comment by Janzert** [comment]
I agree I'd rather not use a hash of the password field. A GUID is probably over kill though, a hex 128 bit random number would be fine. Reusing the activation code would probably even be ok, but that is also already used to prevent some cross site attacks. So a new field is would be best.

Combining the username and secret into one cookie would also be nice. Usernames aren't allowed : in them so that would be fine to use as a separator.

**Comment by bearoff** [comment]
"Using an md5 hash of a database value is not secure"
I thought that in DB we already has crypted password, so md5 over it will be secure enough.

"The guid could be [user name/id]:[salt]"
So as cookie password will be used just salt?

"do the user lookup in the database quickly"
it will be quickly if we'll use id instead of user name, but I suppose it's not fine to show user ids to users )

"I can update the database and make the changes."
Please, to clarify - you will modify all discussed yourself (or only database)?

**Comment by Janzert** [comment]
Heh, now that I re-read McLeopold's message I see he wasn't proposing an actual [UUID](http://en.wikipedia.org/wiki/Universally_unique_identifier) but basically the same thing I did.

> I thought that in DB we already has crypted password, so md5 over it will be secure enough.

Yes, in the database only a hash of the password is stored. But it still not a good idea to expose even a hash of that.

> it will be quickly if we'll use id instead of user name, but I suppose it's not fine to show user ids to users )

user id's are already publicly exposed (see the url for a profile page), using them here is fine

**Comment by McLeopold** [comment]
I'm only planning to add the database field, no php coding.

**Comment by bearoff** [comment]
Ok, tomorrow I'll do as you say. I will use guid as user_id:salt, salt will be generated in way as activation code is generated.
I will use login_cookie column.

Should the login_cookie value be generated once on user register, or only when user logs in first time using "Remember me" checkbox?
I suppose second variant (as we have users w/o this value already).

**Comment by bearoff** [comment]
Fill myself awkwardly as finally i'ts rather you writed this functionality, not me )
But happy to use result, thanks )

**Comment by McLeopold** [comment]
You wrote it, I just cleaned it up.

**Pull request merged**
