### PR TITLE
Fix timer in C++ starter bot

### PR DESCRIPTION
**Pull request by Storyyeller**
The current C++ timer has a number of problems, especially on windows. This change uses pimpl to avoid exposing system headers to rest of bot, switches to use QueryPerformanceCounter on Windows, and adds const correctness.

### CODE REVIEW

**Comment by avdg** [comment]
You have to update the makefile too, because Timer.cpp isn't included to the build list.
Btw, Timer.cpp isn't following the "*.cc" convention from other files, it would be nice if there would be only 1 convention.

**Comment by Storyyeller** [comment]
Sorry, I forgot about the makefile since I don't use it. What is the procedure for changing submissions? Should I update it and then submit a new pull request?

**Comment by avdg** [comment]
Just add the file (I think it shouldn't be hard), commit and push. The pull request will be updated automagically ;-)

**Comment by Storyyeller** [comment]
Ok I updated the makefile and renamed Timer.cpp to Timer.cc. I'm not sure why Timer.cc still shows up though.

**Comment by avdg** [comment]
I think you have to remove that file manually

**Comment by Storyyeller** [comment]
Ok I successfully removed Timer.cpp. I think everything is correct now.

**Pull request closed without merging**
