### PR TITLE
Ruby starter - helper functions, no more r lines

### PR DESCRIPTION
**Pull request by MatmaRex**

### CODE REVIEW

**Comment by amstan** [comment]
Can you just add more commits as you go? And i'll just pull then when you're finished.

**Comment by MatmaRex** [comment]
Alright, that's it. I've actually tested this code, and it worked. I'll concentrate on my own bot now ;)

There are a few more things that could be done, but I think they're better left as an exercise for contestants.

**Comment by sigh** [comment]
The 'r' lines are now deprecated, so that part of the pull request should not be merged :P.

**Comment by MatmaRex** [comment]
_whew_

It's simply discarding them anyway. But lemme fix that.

**Pull request merged**
