### PR TITLE
Add Lua starter bot.

### PR DESCRIPTION
**Pull request by DummySphere**
Hi,
Is it possible to add those two files as the Lua starter package?
It is based on the JavaScript starter package.
Thanks.

### CODE REVIEW

**Comment by McLeopold** [comment]
Can you make the bot do proper parsing of each line rather than just looking at the first 5 characters for "turn" and "ready"?

**Comment by DummySphere** [comment]
It is only for "turn" that the first 5 characters substring is checked (as it is done in the JavaScript starter package), but I can make some changes to check each line command (first word). Is it what you want?

**Comment by McLeopold** [comment]
I've modified the javascript starter to what I would want.  Parsing is done up front without making assumptions on the contents of lines.

**Comment by DummySphere** [comment]
I updated the Lua starter in this way (and removed some complexity in the many if/else in the processLine method).

**Pull request merged**
