### PR TITLE
C# unsafe option added to compiler

### PR DESCRIPTION
**Pull request by IceHarley**
unsafe option allows usage of pointers in C#

### CODE REVIEW

**Comment by amstan** [comment]
What is the reason of this change? Why is it called unsafe?

**Comment by IceHarley** [comment]
The reason is ability to work with pointers mostly for optimization, that is very important in this contest.
The name "unsafe" is because all code in C# (and other .NET languages) called "safe". It means that programmer don't work with memory. But if he needs he can mark some functions as unsafe and it allows to work with pointers. But we need compiler "unsafe" option.
It doesn't mean security, it's all about memory usage. For example C++ is very "unsafe" in this terminology.
Example of usage is hashtables. To fast access record in table we can give offset to pointer to table (like arrays work in C++).

**Comment by amstan** [comment]
@Janzert, can you look over this?

**Comment by Janzert** [comment]
I don't think this will cause any security issue. I do worry slightly that this may be an unusual configuration and could cause people unexpected problems. But I know very little about C# or Mono so I've no real idea if that is a problem or not.

**Comment by IceHarley** [comment]
Janzert, this cannot cause unexpected problems to people because it's just an abililty to use some features. To use them you should obviously mark your function as unsafe. So people that won't use this feature will see no difference.

**Comment by KasperHoldum** [comment]
There should be no need for this in the competition. I did a few tests with this mode in the previous contests. Any gains you would get from enabling unsafe is minimal.However, enabling it will cause no harm at all. It will only affect people that actively use the 'unsafe' keyword inside their code (which I have never seen used in all my time with .NET).

**Comment by IceHarley** [comment]
I already gave examples how it can be used. I never used it before too, but I need it for this challenge, where speed is critical.

**Comment by KasperHoldum** [comment]
You say you need this compiler flag because it's critical for your application, but you do not actually know how it will affect the performance of your code? Try doing a few tests locally and see if you can observe any noticeable performance gains.

C# isn't even working on the server yet, so starting to change compiler options that could add further to the complication all so you perhaps could gain minimal performance on your application seems like a waste at this time.

**Comment by IceHarley** [comment]
It seems you are right. I found way how to workaround unsafe compiler option. I am closing this pull request.
Thanks.

**Pull request closed without merging**
