### PR TITLE
Skip onkeydown event when an input element got focus (fixes #360)

### LINKED ISSUE #360: Annoying prompt window shows up when typing "i" in search user box
Steps to reproduce

1) Go to a page with a game visualizer (for example http://aichallenge.org/visualizer.php?game=77823 )
2) Focus the user search box under the navigation column on the right of the page
3) Type an "i"

This should pop up a prompt window from the game.

Note (bit irrelevant for this issue): Are these shortcuts btw documented?

### PR DESCRIPTION
**Pull request by avdg**

### CODE REVIEW

**Comment by mleise** [comment]
This crashes the Java visualizer, which does not know about document.activeElement

**Comment by avdg** [comment]
Please test if this fix works

I actually didn't look if document was defined for the java visualizer

**Comment by mleise** [comment]
From the looks of it, it might work. Run "ant run-visualizer" and press a key to see if the Java visualizer handles it correctly.

**Comment by avdg** [comment]
Thanks for the hint.

I don't see crashes, so I think its fine.

See #391

**Pull request merged**
