### PR TITLE
A few bugs for python package. Formated code with gofmt.

### PR DESCRIPTION
**Pull request by xarg**
Solves issues #220 and #221
As Effective Go http://golang.org/doc/effective_go.html#formatting recommends I've formatted source files of the Go started package with gofmt tool.

### CODE REVIEW

**Comment by shoenig** [comment]
Less Δ, more characters that can be found on a keyboard.

**Comment by xarg** [comment]
Formatting style argument? No thanks. There is a reason to use a standard formatting style. That is to avoid this kind of arguments.
Those triangle thingies are not my creation. I'm willing to remove all those weird chars and probably contribute more if this pull request passes.

**Comment by shoenig** [comment]
I agree with you, let gofmt do the formatting.

**Comment by DanielVF** [comment]
Tested 66b94de. That looks good.

**Pull request merged**
