### PR TITLE
Ada Starter Pack

### PR DESCRIPTION
**Pull request by philxyz**
I think this covers everything (website change and Ubuntu package installer)

### CODE REVIEW

**Comment by Janzert** [comment]
Does Ada have a problem with MyBot.adb? The MyBot capitalization is the contest standard name unless the language requires a different capitalization.

**Comment by Janzert** [comment]
One other minor thing, the Ada package should be in the worker_setup extra_distribution_languages list. I can fix that though if you don't get it.

**Comment by philxyz** [comment]
Janzert: GNAT issues a warning if you don't use lower case package names for the filenames (for some reason). I didn't see the worker_setup extra_distribution_languages list - if you can fix that easily, that would be great.

**Comment by Janzert** [comment]
Distracted by some other issues at the moment, I do want to get back to this. One thing that would be helpful is a starter bot to test this against. Even if it's not fully functional to the regular starting bots just something that would compile and run through a game even executing no orders just returning "go" to the engine each move would be great.

**Comment by Janzert** [comment]
Heh, sorry. I got so focused on the compiler functionality I forgot you already have the starter bot included here.

**Comment by philxyz** [comment]
Starter bot is included - although all ants change direction when one changes direction because I can find no way of storing the previous bearing of an individual ant. Until the game tells the bot which ants are where as a result of a move, I can't detect it (I think - there must be a way or I'm missing something here :P)

**Comment by amstan** [comment]
Oh man, those license headers are bigger than the contents of the file. Could you move the license in a separate `LICENSE` file?

I hope we can Ada soon!
Thanks

**Comment by philxyz** [comment]
Yeah, I agree the license files are too much - I wasn't sure whether it was meant to be included in all files - it is kind of overkill. I'll sort that when I get back from work (about 10 hours from now)

**Pull request closed without merging**
