### PR TITLE
A basic coffeescript starting pack

### PR DESCRIPTION
**Pull request by aeter**
It may still be quite buggy, and I'm currently fixing some of its bugs; it behaves well against the "play_one_game.sh" script.

### CODE REVIEW

**Comment by amstan** [comment]
What about test_bot.sh? That's what the functional test after compilation does(some starters fail on this).
After that, link me to your entry on aichallengebeta.hypertriangle.com

**Comment by aeter** [comment]
It seems to time out:

adr@cdiemst:~/code/aichallenge/ants$ sh test_bot.sh coffee dist/starter_bots/coffeescript/mybot.coffee 
running for 30 turns
turn    0 bot 0 timed out
turn    0 stats: ant_count: [3, 1]  
score 3 118
status timeout survived
waiting 0.25 seconds for bots to process end turn

I'll send a link once it is improved.
Thanks

**Comment by aeter** [comment]
Sorry, it was because of the bot name (mybot.coffee instead of MyBot.coffee). Now it seems to run OK (with Coffeescript 1.1.1):

adr@cdiemst:~/code/aichallenge/ants$ sh test_bot.sh coffee dist/starter_bots/coffeescript/MyBot.coffee 
running for 30 turns
turn    0 bot 0 timed out
turn    0 stats: ant_count: [3, 1]  
score 3 118
status timeout survived
waiting 0.25 seconds for bots to process end turn

**Comment by aeter** [comment]
It passes the tests now; my profile on the test server is at http://aichallengebeta.hypertriangle.com/profile.php?user=25

The test results:

adr@cdiemst:~/code/aichallenge/ants$ ./test_bot.sh 'coffee dist/starter_bots/coffeescript/MyBot.coffee'
running for 30 turns
turn    0 stats: ant_count: [3, 1]  
turn    1 bot 0 ignored actions:
o 3 18 w # move blocked
turn    1 stats: ant_count: [4, 1]  
turn    2 stats: ant_count: [4, 2]  
turn    3 stats: ant_count: [4, 3]  
turn    4 stats: ant_count: [4, 5]  
turn    5 stats: ant_count: [4, 6]  
turn    6 stats: ant_count: [4, 7]  
turn    7 stats: ant_count: [4, 8]  
turn    8 stats: ant_count: [5, 9]  
turn    9 stats: ant_count: [5, 9]  
turn   10 stats: ant_count: [5, 9]  
turn   11 stats: ant_count: [5, 10]  
turn   12 stats: ant_count: [5, 11]  
turn   13 stats: ant_count: [5, 13]  
turn   14 stats: ant_count: [5, 13]  
turn   15 stats: ant_count: [5, 13]  
turn   16 stats: ant_count: [5, 13]  
turn   17 stats: ant_count: [4, 12]  
turn   18 stats: ant_count: [2, 10]  
turn   19 stats: ant_count: [1, 9]  
turn   20 stats: ant_count: [1, 9]  
turn   21 stats: ant_count: [1, 9]  
turn   22 stats: ant_count: [1, 9]  
turn   23 stats: ant_count: [1, 9]  
turn   24 stats: ant_count: [1, 9]  
turn   25 stats: ant_count: [1, 9]  
turn   26 stats: ant_count: [1, 9]  
turn   27 stats: ant_count: [1, 9]  
turn   28 stats: ant_count: [1, 9]  
turn   29 stats: ant_count: [1, 9]  
turn   30 stats: ant_count: [1, 9]  
score 9 17
status survived survived
waiting 0.25 seconds for bots to process end turn

There are probably left some bugs I wasn't able to find so far.

**Pull request merged**
