### PR TITLE
Java Mapgen

### PR DESCRIPTION
**Pull request by Lundgren**
Added a Java version of symmetric_mapgen.py

### CODE REVIEW

**Comment by amstan** [comment]
Please add the other mapgen that you're working on as well.

**Comment by amstan** [comment]
Any update on this?

**Comment by Lundgren** [comment]
I did continue with it after we spoke last time amstan but I've been busy moving and changing job so I totally forgot about it. Here is what I did before at least. It still needs some work before it's completely useful and I'm happy to help out with that in a week or so when things has calm down for me. 

But please let me know if you guys are still interested in it or if you went in another direction before I spend any more time on it.

**Comment by amstan** [comment]
Just commit what you have so far, what you showed me that day was cool.

That code should be in the repo, regardless of how finished it is.

Thanks, amstan

**Comment by Lundgren** [comment]
The commit I made earlier today contains my latest code.

**Comment by amstan** [comment]
Oh... sorry about that, didn't notice you had new commits.
Pulled everything, and closed.

Thanks for your help.

**Pull request merged**
