### PR TITLE
Double the head/tail length for test runs after compilation

### PR DESCRIPTION
**Pull request by ghost**
See here for the problem this solution fixes: http://aichallenge.org/forums/viewtopic.php?f=21&t=1573

### CODE REVIEW

**Comment by Janzert** [comment]
Just a note before this is merged something will need to be done to ensure the results fit into the database field. Even now at least occasionally the results are too large to fit.

**Comment by McLeopold** [comment]
I don't want to increase the size of the error field in the database.  Maybe we could instead favor the end of the stderr over the start.  256 from head, 768 from tail.

**Comment by ghost** [comment]
+1 @McLeopold

**Comment by ghost** [comment]
Feel free to either accept or close this now, depending on whether you want the functionality of specifying log total length.

**Comment by Janzert** [comment]
Eventually it will be nice to capture a different amount of compiler output than bot output

**Pull request merged**
