### PR TITLE
add racket starter package

### PR DESCRIPTION
**Pull request by stchang**
Added a starter package for the Racket language (racket-lang.org).

### CODE REVIEW

**Comment by Janzert** [comment]
Besides the one line I commented on this looks about ready to merge. I won't have time to do the merge until later tonight, if you haven't had a chance to remove that line before then I'll do it with the merge.

**Comment by stchang** [comment]
Removed the line. Thanks!

On Mon, Nov 28, 2011 at 6:02 PM, Janzert
reply@reply.github.com
wrote:

**Comment by Janzert** [comment]
Thanks I'll be updating the workers in the next hour or two

**Comment by stchang** [comment]
Cool, thanks. Let me know if you run into any problems.

On Tue, Nov 29, 2011 at 12:50 AM, Janzert
reply@reply.github.com
wrote:

**Pull request merged**
